name: 'e2e npm'
on:
  push:
    branches: [main]
jobs:
  test-e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create a React Native app
        run: cd .. && npx create-react-native-app example --yes --use-npm
      - name: Install envy to the React Native app
        run: npm install --save-dev react-native-envy
        working-directory: ../example
      - name: Init envy
        run: npx react-native-envy init
        working-directory: ../example
      - name: Set dev environment
        run: npm run envy:set dev
        working-directory: ../example
      - name: Show the app directory
        run: ([ -e "./src/api.js" ] && [ -e "./settings.json" ] && echo 0 || echo 1) | exit
        working-directory: ../example
