name: Publish github package
# on:
#   release:
#     types: [created]
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Set registry to Github
        run: npm config set registry 'https://npm.pkg.github.com'
      - name: Publish package
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
