name: Publish github package
# on:
#   release:
#     types: [created]
on:
  push:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install modules
        run: npm ci
      - name: Set registry to Github
        run: npm config set registry https://npm.pkg.github.com
      - name: Set auth token
        run: npm config set //npm.pkg.github.com/:_authToken ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        run: npm publish
