name: 'Test e2e'
on:
  push:
    branches: [main]
jobs:
  test-e2e:
    name: Test e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Create a React Native app
        run: cd .. && npx create-react-native-app --yes
      - name: Install envy to the React Native app
        run: cd ../ && pwd && ls
